[WIP][Java] Add Java grpahinfo
alibaba/GraphAr pull request #212
Opened 2023-07-25 08:12 UTC by Thespica

## Proposed changes

This PR aims to implement grpahinfo in Java with [fastFFI](https://github.com/alibaba/fastFFI).

## Known problems
- Can't implement function which return `StdMap`
- Don't konw how to get generic factory like `StdVctor<Property>`
- Test is too simple.

## Plan
### Before 7.30
Make graphinfo's test better(or do it latter?)

### 7.31-8.13
Readers and test.

### 8.14-8.28
Readers and test.

### After 8.28
- Generate JavaDoc
- README in java
- Benchmark?

## Related issue
#72

2023-07-25 10:36 UTC, Thespica commented
`StdMap` error log:
```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ gar-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to /home/john/my-reop-gar/java/target/classes
com.alibaba.fastffi.annotation.FFICodeGenerationException: Cannot find a TypeDef for 
        std::map<std::string, GraphArchive::VertexInfo> -> (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.a
libaba.graphar.stdcxx.StdString,com.alibaba.graphar.graphinfo.VertexInfo>)
during generating
        (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.alibaba.graphar.stdcxx.StdString,com.alibaba.graphar
.graphinfo.VertexInfo>) com.alibaba.graphar.graphinfo.GraphInfo::getVertexInfos()
        at com.alibaba.fastffi.annotation.TypeDefGenerator.reportError(TypeDefGenerator.java:212)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.reportError(TypeDefGenerator.java:208)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.reportError(TypeDefGenerator.java:204)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.getInternalTypeName(TypeDefGenerator.java:1451)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.generateFFIDelegateMethod(TypeDefGenerator.java:2302)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.generateFFIPointer(TypeDefGenerator.java:2004)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.generateFFIPointerOrFFILibrary(TypeDefGenerator.java:780)
        at com.alibaba.fastffi.annotation.TypeDefGenerator.generate(TypeDefGenerator.java:266)
        at com.alibaba.fastffi.annotation.TypeDefRegistry.lambda$generateFFIPointerFFILibrary$2(TypeDefRegistry.java:339)
        at com.alibaba.fastffi.annotation.TypeDefRegistry.processWorklist(TypeDefRegistry.java:325)
        at com.alibaba.fastffi.annotation.TypeDefRegistry.generateFFIPointerFFILibrary(TypeDefRegistry.java:337)
        at com.alibaba.fastffi.annotation.TypeDefRegistry.generate(TypeDefRegistry.java:302)
        at com.alibaba.fastffi.annotation.AnnotationProcessor.process(AnnotationProcessor.java:117)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/john/my-reop-gar/java/src/main/java/com/alibaba/graphar/graphinfo/GraphInfo.java:[197,33] Cannot find a TypeDef for
        std::map<std::string, GraphArchive::VertexInfo> -> (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.a
libaba.graphar.stdcxx.StdString,com.alibaba.graphar.graphinfo.VertexInfo>)
  during generating
        (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.alibaba.graphar.stdcxx.StdString,com.alibaba.graphar
.graphinfo.VertexInfo>) com.alibaba.graphar.graphinfo.GraphInfo::getVertexInfos()
  Type: com.alibaba.graphar.graphinfo.GraphInfo
  Executable: (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.alibaba.graphar.stdcxx.StdString,com.alibaba.g
raphar.graphinfo.VertexInfo>) com.alibaba.graphar.graphinfo.GraphInfo::getVertexInfos()
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.125 s
[ERROR]   during generating
[ERROR]         (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba.fastffi.CXXReference,@com.alibaba.fastffi.FFITypeAlias("std::map<std::string, GraphArchive::VertexInfo>") :: com.alibaba.graphar.stdcxx.StdMap<com.alibaba.graphar.stdcxx.StdString,com.alibaba
.graphar.graphinfo.VertexInfo>) com.alibaba.graphar.graphinfo.GraphInfo::getVertexInfos()
[ERROR]   Type: com.alibaba.graphar.graphinfo.GraphInfo
[ERROR]   Executable: (@com.alibaba.fastffi.FFINameAlias("GetVertexInfos"),@com.alibaba [...]

2023-07-25 10:50 UTC, Thespica commented on java/src/main/java/com/alibaba/graphar/graphinfo/GraphInfo.java
> +  //      StdMap<StdString, VertexInfo> getVertexInfos();
When compile with this function, met error : Cannot find a TypeDef for ....

2023-07-26 08:41 UTC, Thespica commented on java/src/main/java/com/alibaba/graphar/graphinfo/GraphInfo.java
> +  //      StdMap<StdString, VertexInfo> getVertexInfos();
Thanks!
Both ways can solve this problem.

2023-07-31 15:39 UTC, Thespica commented
PTAL :) @acezen @lixueclaire 

I think this PR is ready, but there are some problems when generating docs. In fact, I haven't changed existing docs neither add new docs.

It's maybe related to incompatibility between Python3 and jinja2. We need to discuss it in our weekly meeting.

2023-08-02 02:40 UTC, acezen commented
hi, @Thespica, thanks for the job. Since you has added the unit test for java SDK, I think you should include the test to CI, so we can test the java code in every PR automatically.
The CI you can refer the C++ or Spark in here: https://github.com/alibaba/GraphAr/tree/main/.github/workflows

2023-08-02 03:01 UTC, lixueclaire commented
@Thespica,  thank you for your valuable contribution! In addition to the tests, I believe it would enhance the user experience if a simple example is provided to showcase the usage of the Java SDK. Perhaps, this example could be included when you add the documentation.

2023-08-02 04:24 UTC, Thespica commented
> hi, @Thespica, thanks for the job. Since you has added the unit test for java SDK, I think you should include the test to CI, so we can test the java code in every PR automatically. The CI you can refer the C++ or Spark in here: https://github.com/alibaba/GraphAr/tree/main/.github/workflows

Thanks for your advice! I well do it as soon as possible.

2023-08-02 04:27 UTC, Thespica commented
> @Thespica, thank you for your valuable contribution! In addition to the tests, I believe it would enhance the user experience if a simple example is provided to showcase the usage of the Java SDK. Perhaps, this example could be included when you add the documentation.

Thanks for your advice too!

I think adding examples when adding documentation is better for me.

2023-08-09 01:50 UTC, acezen commented
BTW，the known problem can be recorded in a issue that we can follow in the future.

2023-08-15 10:02 UTC, acezen requested changes
- The Java CI is a liitle complicated，simplify the CI with the builtin llvm and fastFFI. I have create a [java test CI](https://github.com/alibaba/GraphAr/blob/e7a4413c8a34f19e0f6fbbe58781e214d2d4b61d/.github/workflows/java.yml), You can refer to it。
- It's better to write a simple README to tell others that how to `BUILD`, `RUN` and `TEST` the java sdk, you can refer to the README of cpp

2023-08-15 10:45 UTC, acezen commented on java/install-llvm11.sh
> +#!/bin/bash
Remove this file since we don't need to build llvm from the source

2023-08-15 11:16 UTC, acezen commented on java/pom.xml
> +            <version>${fastffi.revision}</version>
add `<classifier>${os.detected.classifier}</classifier>` to install correct jar with os platform.

2023-08-15 11:16 UTC, acezen commented on java/pom.xml
> +            <version>${fastffi.revision}</version>
add <classifier>${os.detected.classifier}</classifier> to install correct jar with os platform.

2023-08-16 03:44 UTC, acezen commented on java/README.md
> +
Add a Working In Progress tag here to tell others that The JAVA SDK is working in progress and unfinished

2023-08-16 03:49 UTC, acezen approved these changes
LGTM~
You can merge after the `WIP` tag add to README

2023-08-16 06:44 UTC, merged